"""v4.0.2 row-level checks.

Revision: eb34e144eb97
Revises: e7a2637c2e20
"""

from collections.abc import Sequence

from alembic import op

revision: str = "eb34e144eb97"
down_revision: str | None = "e7a2637c2e20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        op.f("ck_audit_event_retention_not_before_occurrence"),
        "audit_event",
        "retention_until >= occurred_at",
    )
    op.create_check_constraint(
        op.f("ck_file_upload_purge_not_before_upload"),
        "file_upload",
        "purge_due_at >= uploaded_at",
    )
    op.create_check_constraint(
        op.f("ck_scan_job_modules_not_empty"), "scan_job", "cardinality(modules) >= 1"
    )
    op.create_check_constraint(
        op.f("ck_schedule_modules_not_empty"), "schedule", "cardinality(modules) >= 1"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_schedule_modules_not_empty"), "schedule", type_="check")
    op.drop_constraint(op.f("ck_scan_job_modules_not_empty"), "scan_job", type_="check")
    op.drop_constraint(
        op.f("ck_file_upload_purge_not_before_upload"), "file_upload", type_="check"
    )
    op.drop_constraint(
        op.f("ck_audit_event_retention_not_before_occurrence"),
        "audit_event",
        type_="check",
    )
    # ### end Alembic commands ###
