"""initial schema.

Revision: e7a2637c2e20
Revises: 
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e7a2637c2e20'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('white_label_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    op.create_table('statement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('statement_key', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('response_kind', sa.Enum('acceptance', 'attestation', name='statement_response_kind'), nullable=False),
    sa.Column('required_context_type', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('content_uri', sa.Text(), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement')),
    sa.UniqueConstraint('statement_key', 'version', name=op.f('uq_statement_statement_key_version'))
    )
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('identity_subject', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('email_notifications_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('organization_role', sa.Enum('member', 'organization_admin', name='organization_role'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_app_user_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('identity_subject', name=op.f('uq_app_user_identity_subject'))
    )
    op.create_index(op.f('ix_app_user_organization_id'), 'app_user', ['organization_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('chain_id', sa.Text(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=True),
    sa.Column('envelope_id', sa.Uuid(), nullable=True),
    sa.Column('encryption_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_hash', sa.Text(), nullable=True),
    sa.Column('entry_hash', sa.Text(), nullable=False),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('detail IS NOT NULL OR payload_encrypted IS NOT NULL', name=op.f('ck_audit_event_detail_or_payload')),
    sa.CheckConstraint('num_nonnulls(payload_encrypted, wrapped_dek, envelope_id, encryption_metadata) IN (0, 4)', name=op.f('ck_audit_event_payload_group_all_or_none')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_audit_event_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event')),
    sa.UniqueConstraint('chain_id', 'sequence_number', name=op.f('uq_audit_event_chain_id_sequence_number'))
    )
    op.create_index(op.f('ix_audit_event_organization_id'), 'audit_event', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_event_retention_until'), 'audit_event', ['retention_until'], unique=False)
    op.create_table('statement_response',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('statement_id', sa.Uuid(), nullable=False),
    sa.Column('envelope_id', sa.Uuid(), nullable=False),
    sa.Column('context_type', sa.Text(), nullable=True),
    sa.Column('context_id', sa.Uuid(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_evidence_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_dek', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('(context_type IS NULL) = (context_id IS NULL)', name=op.f('ck_statement_response_context_named_and_bound')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_statement_response_organization_id_organization')),
    sa.ForeignKeyConstraint(['statement_id'], ['statement.id'], name=op.f('fk_statement_response_statement_id_statement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement_response'))
    )
    op.create_index(op.f('ix_statement_response_organization_id'), 'statement_response', ['organization_id'], unique=False)
    op.create_index(op.f('ix_statement_response_statement_id'), 'statement_response', ['statement_id'], unique=False)
    op.create_index('uq_statement_response_account_level', 'statement_response', ['statement_id', 'envelope_id'], unique=True, postgresql_where=sa.text('context_type IS NULL'))
    op.create_index('uq_statement_response_contextual', 'statement_response', ['statement_id', 'context_type', 'context_id'], unique=True, postgresql_where=sa.text('context_type IS NOT NULL'))
    op.create_table('api_key',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('scope', sa.Enum('read_only', 'full_scan', name='api_key_scope'), nullable=False),
    sa.Column('key_prefix', sa.Text(), nullable=False),
    sa.Column('secret_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revocation_reason IS NULL OR revoked_at IS NOT NULL', name=op.f('ck_api_key_reason_implies_revocation')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_api_key_created_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_api_key_organization_id_organization')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_api_key_owner_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_key')),
    sa.UniqueConstraint('key_prefix', name=op.f('uq_api_key_key_prefix'))
    )
    op.create_index(op.f('ix_api_key_created_by_user_id'), 'api_key', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_api_key_organization_id'), 'api_key', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_key_owner_user_id'), 'api_key', ['owner_user_id'], unique=False)
    op.create_table('asset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Enum('domain', name='asset_type'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('origin', sa.Enum('added', 'discovered', name='asset_origin'), nullable=False),
    sa.Column('parent_asset_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('regression_alerts_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parent_asset_id IS NULL OR origin = 'discovered'", name=op.f('ck_asset_child_implies_discovered')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_asset_created_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_asset_organization_id_organization')),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['asset.id'], name=op.f('fk_asset_parent_asset_id_asset'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset')),
    sa.UniqueConstraint('organization_id', 'asset_type', 'value', name=op.f('uq_asset_organization_id_asset_type_value'))
    )
    op.create_index(op.f('ix_asset_created_by_user_id'), 'asset', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_asset_parent_asset_id'), 'asset', ['parent_asset_id'], unique=False)
    op.create_table('file_upload',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('declared_mime_type', sa.Text(), nullable=True),
    sa.Column('detected_mime_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purge_due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("purge_due_at <= uploaded_at + interval '24 hours'", name=op.f('ck_file_upload_purge_within_24_hours')),
    sa.CheckConstraint('(purged_at IS NULL) = (storage_key IS NOT NULL)', name=op.f('ck_file_upload_storage_key_while_bytes_exist')),
    sa.CheckConstraint('uploaded_by_user_id IS NULL OR organization_id IS NOT NULL', name=op.f('ck_file_upload_uploader_implies_org')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_file_upload_organization_id_organization')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['app_user.id'], name=op.f('fk_file_upload_uploaded_by_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_upload'))
    )
    op.create_index(op.f('ix_file_upload_organization_id'), 'file_upload', ['organization_id'], unique=False)
    op.create_index(op.f('ix_file_upload_purge_due_at'), 'file_upload', ['purge_due_at'], unique=False)
    op.create_index(op.f('ix_file_upload_uploaded_by_user_id'), 'file_upload', ['uploaded_by_user_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_notification_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('organization_invitation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('organization_role', sa.Enum('member', 'organization_admin', name='organization_role'), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('accepted_by_user_id IS NULL OR accepted_at IS NOT NULL', name=op.f('ck_organization_invitation_acceptance_actor_implies_time')),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['app_user.id'], name=op.f('fk_organization_invitation_accepted_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['app_user.id'], name=op.f('fk_organization_invitation_invited_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_organization_invitation_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_invitation')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_organization_invitation_token_hash'))
    )
    op.create_index(op.f('ix_organization_invitation_accepted_by_user_id'), 'organization_invitation', ['accepted_by_user_id'], unique=False)
    op.create_index(op.f('ix_organization_invitation_invited_by_user_id'), 'organization_invitation', ['invited_by_user_id'], unique=False)
    op.create_index(op.f('ix_organization_invitation_organization_id'), 'organization_invitation', ['organization_id'], unique=False)
    op.create_index('uq_organization_invitation_live_email', 'organization_invitation', ['organization_id', sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.create_table('organization_webhook',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_url_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('signing_secret_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_organization_webhook_created_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_organization_webhook_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_webhook')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_organization_webhook_organization_id'))
    )
    op.create_index(op.f('ix_organization_webhook_created_by_user_id'), 'organization_webhook', ['created_by_user_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.Enum('executive', 'technical', name='report_tier'), nullable=False),
    sa.Column('technical_view', sa.Enum('full', 'summary', name='technical_report_view'), nullable=True),
    sa.Column('format', sa.Enum('pdf', 'docx', 'json', name='report_format'), nullable=False),
    sa.Column('language', sa.Enum('en', 'fr', 'de', name='report_language'), nullable=False),
    sa.Column('source_scan_job_id', sa.Uuid(), nullable=True),
    sa.Column('source_scan_task_id', sa.Uuid(), nullable=True),
    sa.Column('generated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tier = 'technical' OR technical_view IS NULL", name=op.f('ck_report_view_is_technical_only')),
    sa.CheckConstraint('num_nonnulls(source_scan_job_id, source_scan_task_id) = 1', name=op.f('ck_report_one_source')),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['app_user.id'], name=op.f('fk_report_generated_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_report_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    op.create_index(op.f('ix_report_generated_by_user_id'), 'report', ['generated_by_user_id'], unique=False)
    op.create_index(op.f('ix_report_organization_id'), 'report', ['organization_id'], unique=False)
    op.create_table('asset_feed',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.Enum('rss', 'atom', name='feed_format'), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_asset_feed_asset_id_asset'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_asset_feed_created_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_asset_feed_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_feed'))
    )
    op.create_index(op.f('ix_asset_feed_asset_id'), 'asset_feed', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_feed_created_by_user_id'), 'asset_feed', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_asset_feed_organization_id'), 'asset_feed', ['organization_id'], unique=False)
    op.create_index(op.f('ix_asset_feed_token_hash'), 'asset_feed', ['token_hash'], unique=False)
    op.create_table('domain_verification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('verified_scope', sa.Enum('exact', 'zone', name='verification_scope'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_domain_verification_asset_id_asset'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_domain_verification_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_verification')),
    sa.UniqueConstraint('asset_id', name=op.f('uq_domain_verification_asset_id'))
    )
    op.create_index(op.f('ix_domain_verification_organization_id'), 'domain_verification', ['organization_id'], unique=False)
    op.create_table('domain_verification_challenge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('requested_scope', sa.Enum('exact', 'zone', name='verification_scope'), nullable=False),
    sa.Column('record_type', sa.Enum('TXT', name='dns_record_type'), nullable=False),
    sa.Column('record_name', sa.Text(), nullable=False),
    sa.Column('verification_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_recheck_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.CheckConstraint('failure_code IS NULL OR last_recheck_at IS NOT NULL', name=op.f('ck_domain_verification_challenge_failure_follows_recheck')),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_domain_verification_challenge_asset_id_asset'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_domain_verification_challenge_organization_id_organization')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['app_user.id'], name=op.f('fk_domain_verification_challenge_requested_by_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_verification_challenge')),
    sa.UniqueConstraint('asset_id', name=op.f('uq_domain_verification_challenge_asset_id'))
    )
    op.create_index(op.f('ix_domain_verification_challenge_organization_id'), 'domain_verification_challenge', ['organization_id'], unique=False)
    op.create_index(op.f('ix_domain_verification_challenge_requested_by_user_id'), 'domain_verification_challenge', ['requested_by_user_id'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('modules', postgresql.ARRAY(sa.Enum('email', 'web', 'file', 'pqc', 'dnssec', name='scan_module')), nullable=False),
    sa.Column('module_configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('recurrence_rule', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_schedule_asset_id_asset'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_schedule_created_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_schedule_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule'))
    )
    op.create_index(op.f('ix_schedule_asset_id'), 'schedule', ['asset_id'], unique=False)
    op.create_index(op.f('ix_schedule_created_by_user_id'), 'schedule', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_schedule_next_run_at'), 'schedule', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedule_organization_id'), 'schedule', ['organization_id'], unique=False)
    op.create_table('scan_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('guest', 'manual', 'schedule', 'api', name='scan_source'), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('api_key_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('target_domain', sa.Text(), nullable=True),
    sa.Column('file_upload_id', sa.Uuid(), nullable=True),
    sa.Column('modules', postgresql.ARRAY(sa.Enum('email', 'web', 'file', 'pqc', 'dnssec', name='scan_module')), nullable=False),
    sa.Column('module_configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'partial', 'failed', 'canceled', name='scan_job_status'), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('claim_token_hash', sa.Text(), nullable=True),
    sa.Column('claimed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(purge_at IS NOT NULL) = (status IN ('completed', 'partial', 'failed', 'canceled') OR (source = 'guest' AND claimed_at IS NULL))", name=op.f('ck_scan_job_purge_deadline_placement')),
    sa.CheckConstraint("(source = 'api') = (api_key_id IS NOT NULL)", name=op.f('ck_scan_job_api_key_provenance')),
    sa.CheckConstraint("(source = 'schedule') = (schedule_id IS NOT NULL)", name=op.f('ck_scan_job_schedule_provenance')),
    sa.CheckConstraint("(status IN ('completed', 'partial', 'failed', 'canceled')) = (finished_at IS NOT NULL)", name=op.f('ck_scan_job_terminal_state_has_finish')),
    sa.CheckConstraint("claim_token_hash IS NULL OR source = 'guest'", name=op.f('ck_scan_job_guest_only_claimable')),
    sa.CheckConstraint("organization_id IS NOT NULL OR source = 'guest'", name=op.f('ck_scan_job_only_guest_lacks_org')),
    sa.CheckConstraint("source <> 'guest' OR claimed_at IS NOT NULL OR claim_token_hash IS NOT NULL", name=op.f('ck_scan_job_unclaimed_guest_holds_hash')),
    sa.CheckConstraint("status <> 'running' OR started_at IS NOT NULL", name=op.f('ck_scan_job_running_has_start')),
    sa.CheckConstraint("target_domain IS NULL OR source = 'guest'", name=op.f('ck_scan_job_guest_only_target_text')),
    sa.CheckConstraint('claimed_at IS NULL OR claim_token_hash IS NULL', name=op.f('ck_scan_job_claim_discards_hash')),
    sa.CheckConstraint('claimed_at IS NULL OR organization_id IS NOT NULL', name=op.f('ck_scan_job_claimed_job_has_org')),
    sa.CheckConstraint('claimed_by_user_id IS NULL OR claimed_at IS NOT NULL', name=op.f('ck_scan_job_claim_actor_implies_time')),
    sa.CheckConstraint('num_nonnulls(asset_id, target_domain, file_upload_id) = 1', name=op.f('ck_scan_job_one_launch_target')),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], name=op.f('fk_scan_job_api_key_id_api_key')),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name=op.f('fk_scan_job_asset_id_asset'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['app_user.id'], name=op.f('fk_scan_job_claimed_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_upload_id'], ['file_upload.id'], name=op.f('fk_scan_job_file_upload_id_file_upload')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_scan_job_organization_id_organization')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name=op.f('fk_scan_job_schedule_id_schedule')),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['app_user.id'], name=op.f('fk_scan_job_triggered_by_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_job')),
    sa.UniqueConstraint('file_upload_id', name=op.f('uq_scan_job_file_upload_id'))
    )
    op.create_index(op.f('ix_scan_job_api_key_id'), 'scan_job', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_scan_job_asset_id'), 'scan_job', ['asset_id'], unique=False)
    op.create_index(op.f('ix_scan_job_claimed_by_user_id'), 'scan_job', ['claimed_by_user_id'], unique=False)
    op.create_index(op.f('ix_scan_job_organization_id'), 'scan_job', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scan_job_purge_at'), 'scan_job', ['purge_at'], unique=False)
    op.create_index(op.f('ix_scan_job_schedule_id'), 'scan_job', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_scan_job_triggered_by_user_id'), 'scan_job', ['triggered_by_user_id'], unique=False)
    op.create_table('key_envelope',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Enum('organization', 'user', 'scan_job', name='key_scope'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('scan_job_id', sa.Uuid(), nullable=True),
    sa.Column('wrapped_kek', sa.LargeBinary(), nullable=False),
    sa.Column('wrapping_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('wrapping_algorithm', sa.Text(), nullable=False),
    sa.Column('master_key_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(scope = 'scan_job') = (organization_id IS NULL)", name=op.f('ck_key_envelope_guest_scope_lacks_org')),
    sa.CheckConstraint("(scope = 'scan_job') = (scan_job_id IS NOT NULL)", name=op.f('ck_key_envelope_scan_job_scope_has_job')),
    sa.CheckConstraint("(scope = 'user') = (user_id IS NOT NULL)", name=op.f('ck_key_envelope_user_scope_has_user')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_key_envelope_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_job.id'], name=op.f('fk_key_envelope_scan_job_id_scan_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_key_envelope_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_key_envelope')),
    sa.UniqueConstraint('scan_job_id', name=op.f('uq_key_envelope_scan_job_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_key_envelope_user_id'))
    )
    op.create_index(op.f('ix_key_envelope_organization_id'), 'key_envelope', ['organization_id'], unique=False)
    op.create_index('uq_key_envelope_organization_scope', 'key_envelope', ['organization_id'], unique=True, postgresql_where=sa.text("scope = 'organization'"))
    op.create_table('scan_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('scan_job_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('module', sa.Enum('email', 'web', 'file', 'pqc', 'dnssec', name='scan_module'), nullable=False),
    sa.Column('test_key', sa.Text(), nullable=False),
    sa.Column('test_version', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('non_intrusive', 'intrusive', 'not_applicable', name='scan_classification'), nullable=False),
    sa.Column('target_asset_id', sa.Uuid(), nullable=True),
    sa.Column('target_domain', sa.Text(), nullable=True),
    sa.Column('file_upload_id', sa.Uuid(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', 'skipped', 'blocked', 'canceled', name='scan_task_status'), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(file_upload_id IS NOT NULL) = (module = 'file')", name=op.f('ck_scan_task_file_task_targets_upload')),
    sa.CheckConstraint("(module = 'file') = (classification = 'not_applicable')", name=op.f('ck_scan_task_not_applicable_is_file_only')),
    sa.CheckConstraint("(status IN ('completed', 'failed', 'skipped', 'blocked', 'canceled')) = (finished_at IS NOT NULL)", name=op.f('ck_scan_task_terminal_state_has_finish')),
    sa.CheckConstraint("status <> 'blocked' OR status_reason IS NOT NULL", name=op.f('ck_scan_task_blocked_says_why')),
    sa.CheckConstraint("status <> 'running' OR started_at IS NOT NULL", name=op.f('ck_scan_task_running_has_start')),
    sa.CheckConstraint('num_nonnulls(target_asset_id, target_domain, file_upload_id) = 1', name=op.f('ck_scan_task_one_task_target')),
    sa.ForeignKeyConstraint(['file_upload_id'], ['file_upload.id'], name=op.f('fk_scan_task_file_upload_id_file_upload')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_scan_task_organization_id_organization')),
    sa.ForeignKeyConstraint(['parent_task_id'], ['scan_task.id'], name=op.f('fk_scan_task_parent_task_id_scan_task')),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_job.id'], name=op.f('fk_scan_task_scan_job_id_scan_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['asset.id'], name=op.f('fk_scan_task_target_asset_id_asset'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_task'))
    )
    op.create_index(op.f('ix_scan_task_file_upload_id'), 'scan_task', ['file_upload_id'], unique=False)
    op.create_index(op.f('ix_scan_task_organization_id'), 'scan_task', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scan_task_parent_task_id'), 'scan_task', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_scan_task_scan_job_id'), 'scan_task', ['scan_job_id'], unique=False)
    op.create_index(op.f('ix_scan_task_target_asset_id'), 'scan_task', ['target_asset_id'], unique=False)
    op.create_table('scan_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('scan_task_id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('grade', sa.Enum('A+', 'A', 'B', 'C', 'D', 'F', name='scan_grade'), nullable=True),
    sa.Column('severity_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_scan_result_organization_id_organization')),
    sa.ForeignKeyConstraint(['scan_task_id'], ['scan_task.id'], name=op.f('fk_scan_result_scan_task_id_scan_task'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_result')),
    sa.UniqueConstraint('scan_task_id', name=op.f('uq_scan_result_scan_task_id'))
    )
    op.create_index(op.f('ix_scan_result_organization_id'), 'scan_result', ['organization_id'], unique=False)
    op.create_table('finding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('scan_result_id', sa.Uuid(), nullable=False),
    sa.Column('check_id', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'info', name='finding_severity'), nullable=False),
    sa.Column('status', sa.Enum('new', 'regression', 'persistent', 'resolved', name='finding_status'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_resource', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_references', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_finding_organization_id_organization')),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_result.id'], name=op.f('fk_finding_scan_result_id_scan_result'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding'))
    )
    op.create_index(op.f('ix_finding_organization_id'), 'finding', ['organization_id'], unique=False)
    op.create_index('ix_finding_result_check', 'finding', ['scan_result_id', 'check_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_finding_result_check', table_name='finding')
    op.drop_index(op.f('ix_finding_organization_id'), table_name='finding')
    op.drop_table('finding')
    op.drop_index(op.f('ix_scan_result_organization_id'), table_name='scan_result')
    op.drop_table('scan_result')
    op.drop_index(op.f('ix_scan_task_target_asset_id'), table_name='scan_task')
    op.drop_index(op.f('ix_scan_task_scan_job_id'), table_name='scan_task')
    op.drop_index(op.f('ix_scan_task_parent_task_id'), table_name='scan_task')
    op.drop_index(op.f('ix_scan_task_organization_id'), table_name='scan_task')
    op.drop_index(op.f('ix_scan_task_file_upload_id'), table_name='scan_task')
    op.drop_table('scan_task')
    op.drop_index('uq_key_envelope_organization_scope', table_name='key_envelope', postgresql_where=sa.text("scope = 'organization'"))
    op.drop_index(op.f('ix_key_envelope_organization_id'), table_name='key_envelope')
    op.drop_table('key_envelope')
    op.drop_index(op.f('ix_scan_job_triggered_by_user_id'), table_name='scan_job')
    op.drop_index(op.f('ix_scan_job_schedule_id'), table_name='scan_job')
    op.drop_index(op.f('ix_scan_job_purge_at'), table_name='scan_job')
    op.drop_index(op.f('ix_scan_job_organization_id'), table_name='scan_job')
    op.drop_index(op.f('ix_scan_job_claimed_by_user_id'), table_name='scan_job')
    op.drop_index(op.f('ix_scan_job_asset_id'), table_name='scan_job')
    op.drop_index(op.f('ix_scan_job_api_key_id'), table_name='scan_job')
    op.drop_table('scan_job')
    op.drop_index(op.f('ix_schedule_organization_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_next_run_at'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_created_by_user_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_asset_id'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_domain_verification_challenge_requested_by_user_id'), table_name='domain_verification_challenge')
    op.drop_index(op.f('ix_domain_verification_challenge_organization_id'), table_name='domain_verification_challenge')
    op.drop_table('domain_verification_challenge')
    op.drop_index(op.f('ix_domain_verification_organization_id'), table_name='domain_verification')
    op.drop_table('domain_verification')
    op.drop_index(op.f('ix_asset_feed_token_hash'), table_name='asset_feed')
    op.drop_index(op.f('ix_asset_feed_organization_id'), table_name='asset_feed')
    op.drop_index(op.f('ix_asset_feed_created_by_user_id'), table_name='asset_feed')
    op.drop_index(op.f('ix_asset_feed_asset_id'), table_name='asset_feed')
    op.drop_table('asset_feed')
    op.drop_index(op.f('ix_report_organization_id'), table_name='report')
    op.drop_index(op.f('ix_report_generated_by_user_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_organization_webhook_created_by_user_id'), table_name='organization_webhook')
    op.drop_table('organization_webhook')
    op.drop_index('uq_organization_invitation_live_email', table_name='organization_invitation', postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.drop_index(op.f('ix_organization_invitation_organization_id'), table_name='organization_invitation')
    op.drop_index(op.f('ix_organization_invitation_invited_by_user_id'), table_name='organization_invitation')
    op.drop_index(op.f('ix_organization_invitation_accepted_by_user_id'), table_name='organization_invitation')
    op.drop_table('organization_invitation')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_file_upload_uploaded_by_user_id'), table_name='file_upload')
    op.drop_index(op.f('ix_file_upload_purge_due_at'), table_name='file_upload')
    op.drop_index(op.f('ix_file_upload_organization_id'), table_name='file_upload')
    op.drop_table('file_upload')
    op.drop_index(op.f('ix_asset_parent_asset_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_created_by_user_id'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_api_key_owner_user_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_organization_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_created_by_user_id'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index('uq_statement_response_contextual', table_name='statement_response', postgresql_where=sa.text('context_type IS NOT NULL'))
    op.drop_index('uq_statement_response_account_level', table_name='statement_response', postgresql_where=sa.text('context_type IS NULL'))
    op.drop_index(op.f('ix_statement_response_statement_id'), table_name='statement_response')
    op.drop_index(op.f('ix_statement_response_organization_id'), table_name='statement_response')
    op.drop_table('statement_response')
    op.drop_index(op.f('ix_audit_event_retention_until'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_organization_id'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_app_user_organization_id'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('statement')
    op.drop_table('organization')

    # Hand-added: autogenerate creates the PostgreSQL enum types through
    # create_table but never drops them on downgrade. Without these, the
    # downgrade-then-upgrade round trip dies on "type already exists".
    for enum_type in (
        'organization_role',
        'key_scope',
        'asset_type',
        'asset_origin',
        'verification_scope',
        'dns_record_type',
        'statement_response_kind',
        'scan_source',
        'scan_job_status',
        'scan_module',
        'scan_classification',
        'scan_task_status',
        'scan_grade',
        'finding_severity',
        'finding_status',
        'api_key_scope',
        'report_tier',
        'technical_report_view',
        'report_format',
        'report_language',
        'feed_format',
    ):
        sa.Enum(name=enum_type).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
